//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrLuje.LazyPackagesCleaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDeleteOnFirstBuild {
            get {
                return ((bool)(this["EnableDeleteOnFirstBuild"]));
            }
            set {
                this["EnableDeleteOnFirstBuild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDeleteOnClean {
            get {
                return ((bool)(this["EnableDeleteOnClean"]));
            }
            set {
                this["EnableDeleteOnClean"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(.+)(CompanyName)([\\.\\w]+)(\\.[0-9]+){3}(\\\\lib\\\\.+\\.dll\\</HintPath\\>)")]
        public string RegexProjectReferencePattern {
            get {
                return ((string)(this["RegexProjectReferencePattern"]));
            }
            set {
                this["RegexProjectReferencePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$1$2$3$5")]
        public string RegexProjectReferenceReplace {
            get {
                return ((string)(this["RegexProjectReferenceReplace"]));
            }
            set {
                this["RegexProjectReferenceReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(id=\")(?<name>[^\"]*)(\" version=\")(?<version>[^\"]*)(\")")]
        public string RegexPackageConfigPackagePattern {
            get {
                return ((string)(this["RegexPackageConfigPackagePattern"]));
            }
            set {
                this["RegexPackageConfigPackagePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(<reference include=\")(CompanyName)[^,]*)[^\"]*\"")]
        public string RegexProjectReferenceProcessPattern {
            get {
                return ((string)(this["RegexProjectReferenceProcessPattern"]));
            }
            set {
                this["RegexProjectReferenceProcessPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$1$2\"")]
        public string RegexProjectReferenceProcessReplace {
            get {
                return ((string)(this["RegexProjectReferenceProcessReplace"]));
            }
            set {
                this["RegexProjectReferenceProcessReplace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableFullPackageCleanOnFixConfig {
            get {
                return ((bool)(this["EnableFullPackageCleanOnFixConfig"]));
            }
            set {
                this["EnableFullPackageCleanOnFixConfig"] = value;
            }
        }
    }
}
